name: clang_format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'clang-format flightlib'
      uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: './flightlib'
        exclude: './flightlib/externals  ./flightlib/include/flightlib/json'
        clangFormatVersion: 6
