topics:
  quad_name: "kingfisher"
  state: "dodgeros_pilot/state"
  obstacles: "dodgeros_pilot/groundtruth/obstacles"
  start: "start_navigation"
  finish: "finish_navigation"
  skip_trial: "skip_trial"

# target: 50 # goal distance in x-direction, must be INTEGER
timeout: 55  # after [timeout] seconds without arriving at the desired distance in x direction, the episode is considered a failure
bounding_box: [-5, 65, -30, 30, 0, 30] # when exiting this bounding box, the episode is considered a failure

crashed_thr: 0.1 # 10 cm from a point is crash

# if you really don't want the cool plots, put this to False
plots: False
