position_controller:
  use_rate_mode: false

  kpxy: 6.0
  kdxy: 4.0

  kpz: 6.0
  kdz: 4.0
  krp: 6.0
  kyaw: 4.0

  pxy_error_max: 1.0
  vxy_error_max: 3.0
  pz_error_max: 1.0
  vz_error_max: 2.0
  yaw_error_max: 0.7

  perform_aerodynamics_compensation: false

  k_drag_x: 0.0
  k_drag_y: 0.0
  k_drag_z: 0.0
  k_thrust_horz: 0.0
