<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>envsim</name>
    <version>0.0.1</version>
    <description>ROS 2 Wrapper for Dodgelib Simulator</description>

    <maintainer email="song@ifi.uzh.ch">Yunlong Song</maintainer>

    <license>GNU GPL</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>std_msgs</depend>
    <depend>nav_msgs</depend>
    <depend>sensor_msgs</depend>
    <depend>geometry_msgs</depend>
    <depend>cv_bridge</depend>
    <depend>image_transport</depend>
    <depend>pcl_conversions</depend>
    <depend>pcl_ros</depend>
    <depend>tf2</depend>
    <depend>tf2_ros</depend>
    <depend>rosgraph_msgs</depend>
    <depend>dodgelib</depend>
    <depend>dodgeros</depend>
    <depend>envsim_msgs</depend>
    <depend>dodgeros_msgs</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>